version: "3.8"
services:
  devcontainer:
    build:
      context: ./..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
